XLabsProject/iw4x-client

- README.md
- appveyor.yml
This pull requests adds CI configuration for AppVeyor to allow code to be automatically built on this repository and in future pull requests on a public infrastructure.
> AppVeyor CI integration

- src/Components/Modules/Auth.cpp
- src/Components/Modules/Auth.hpp
- src/Components/Modules/QuickPatch.cpp
> Generate new key if player guid has been shared.

- src/Components/Modules/QuickPatch.cpp
In order to function as intended GSC needs to be updated.
> [QuickPatch] Add intermission time dvar

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Client.cpp
- src/Components/Modules/Client.hpp
- src/Components/Modules/Dvar.cpp
- src/Components/Modules/FileSystem.cpp
- src/Components/Modules/FileSystem.hpp
- src/Components/Modules/Maps.cpp
- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/QuickPatch.hpp
- src/Components/Modules/Script.cpp
- src/Components/Modules/Script.hpp
- src/Components/Modules/Zones.cpp
- src/Utils/CSV.cpp
**Functions**: _fileWrite_, _fileRead_, _fileExists_, _fileRemove_
**Methods**: _getIP_, _getPing_
**Dvars**: _g_playerCollision_, _g_playerEjection_, _r_specularCustomMaps_
There are some changes to the general code too.
> Added new gsc functions and methods, dvars and changed some code.

- src/Components/Modules/Bots.cpp
- src/Components/Modules/Bots.hpp
- src/Components/Modules/Network.cpp
- src/Components/Modules/Network.hpp
- src/Components/Modules/Node.cpp
- src/Components/Modules/Node.hpp
- src/Components/Modules/Script.cpp
- src/Components/Modules/Script.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
Includes #45
Adds several GSC functions:
- <bot> botMovement(<int>, <int>);
- <bot> botAction(<str action>);
- <bot> botWeapon(<str>);
- <bot> botStop();
- <bot> isBot();
- <bot> SetPing(<int>)
> Bot GSC functions for bots pressing buttons and moving

- CHANGELOG.md
- src/Components/Modules/Changelog.cpp
- src/Components/Modules/Maps.cpp
- src/Components/Modules/News.cpp
- src/Components/Modules/News.hpp
- src/Utils/Cache.cpp
Courtesy of @Dss0 
- Removed old updater code since it's no longer maintained
- Removed old onion urls
- Fetch changelog from github
- Open iw4x support page on xlabs.dev site when clicking the store button
- Updated Changelog
> Remove updater, update changelog and links

- CHANGELOG.md
- src/Steam/Proxy.cpp
- src/Steam/Proxy.hpp
- src/Steam/Steam.cpp
- Update changelog
- Temp fix for steam integration
Courtesy of @Dss0
> Fix Steam Presence

- src/Components/Modules/IW4MVM.cpp
- src/Components/Modules/Script.cpp
- src/Components/Modules/Script.hpp
- src/Main.cpp
Previous iterations will notify when hitches occur.
> Adds hitch warnings

- CHANGELOG.md
- src/Components/Modules/Exception.cpp
- src/Components/Modules/Localization.cpp
Courtesy of @Dss0 
- Removed Crash Helper
- Added new Contributors to Credits
- Updated Changelog
> Update Credits & Changelog, Remove Crash-Helper

- src/Components/Modules/Localization.cpp
Get rid of /dev/dev/ & add Louvenarde
> [Credits] Add contributor + Fix

- src/Components/Modules/Dvar.cpp
> [Dvar] Unlock camera_thirdPersonCrosshairOffset

- src/Components/Modules/AssetInterfaces/IMaterial.cpp
Small update to fix holes in wall in chinatown and broadcast, probably other maps :)
The techset matching is not perfect yet, some chinatown cloth have visible Z-Fight
> Corrected wc_unlit matching and a few others

- src/Components/Modules/AssetInterfaces/IMaterial.cpp
> Fix compile

- src/Components/Modules/Zones.cpp
Apply 448 patches to 446 too
Add 446 and 461 shader constants mappings
> Some change for loading codo maps

- README.md
- generate.bat
- premake5.lua
- src/Components/Modules/QuickPatch.cpp
This commit elaborates on #93 as a new define was added to the source.
This commit should simplify the process as it adds an extra option to the premake.lua file.
> New Premake option. Improved asm

- src/Components/Modules/Command.cpp
- src/Components/Modules/QuickPatch.cpp
- src/STDInclude.hpp
- src/Steam/Proxy.cpp
- src/Utils/Library.cpp
- src/Utils/Library.hpp
And re-wrote quit_hard command ( Will cause BSOD like original authors intended )
> Added functionalities to Library class (from S1X).

- src/Components/Modules/QuickPatch.cpp
- src/Steam/Proxy.cpp
- src/Utils/Library.cpp
- src/Utils/Library.hpp
#96 [https://github.com/XLabsProject/iw4x-client/pull/96#commitcomment-53776529](url)
To be honest some of the classes are in camel and some are in pascalcase. I made the library class entirely pascalcase because it seems the majority of classes here follow that style
> Changing the style to PascalCase

- src/Components/Modules/Maps.cpp
https://github.com/XLabsProject/iw4x-rawfiles/pull/2
> Added DLC#9 (Classics pack 3)

- generate.bat
- src/Components/Modules/AntiCheat.cpp
The crash command is not needed
> Disable anticheatby default

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Dvar.cpp
- src/Components/Modules/Dvar.hpp
- src/Components/Modules/IW4MVM.cpp
- src/Components/Modules/Maps.cpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
Setraw functions have been removed of course
> [Dvar] Use set raw method on dvars by default

- src/Game/Structs.hpp
My bad, I could have sworn i properly separated the two prs in different branches but I messed up.
> I accidentally modifed the struct

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Dedicated.hpp
- src/Components/Modules/Logger.cpp
- src/Components/Modules/Logger.hpp
- src/Components/Modules/Renderer.cpp
- src/Components/Modules/Script.cpp
- src/Components/Modules/ZoneBuilder.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
Should be an improvement as it's easier to use an enum over numbers that you have to remember
> [Logger] Use correct enum over numbers for com_error

- src/Components/Modules/Auth.cpp
- src/Components/Modules/Bots.cpp
- src/Components/Modules/Changelog.cpp
- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Maps.cpp
- src/Components/Modules/Node.cpp
- src/Components/Modules/ServerInfo.cpp
- src/Components/Modules/ServerList.cpp
- src/Game/Functions.hpp
- src/Utils/CSV.cpp
- src/Utils/InfoString.cpp
- src/Utils/InfoString.hpp
- src/Utils/String.cpp
- src/Utils/String.hpp
> Refactor some utils

- src/Components/Modules/Flags.cpp
- src/Components/Modules/Flags.hpp
- src/Utils/String.cpp
- src/Utils/String.hpp
- src/Utils/Utils.cpp
- src/Utils/WebIO.cpp
- src/Utils/WebIO.hpp
Changes coming from S1x and IW6x
> [Utils] Refactor

- src/Components/Modules/AntiCheat.cpp
- src/Components/Modules/AssetInterfaces/IFont_s.cpp
- src/Utils/Memory.hpp
> [IFont] Use Zone allocator instead of static mem allocator

- src/Components/Modules/Auth.cpp
- src/Components/Modules/Bans.cpp
- src/Components/Modules/Bots.cpp
- src/Components/Modules/CardTitles.cpp
- src/Components/Modules/Chat.cpp
- src/Components/Modules/Clantags.cpp
- src/Components/Modules/ClientCommand.cpp
- src/Components/Modules/Command.cpp
- src/Components/Modules/Command.hpp
- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Dvar.cpp
- src/Components/Modules/Exception.cpp
- src/Components/Modules/FastFiles.cpp
- src/Components/Modules/Friends.cpp
- src/Components/Modules/Gamepad.cpp
- src/Components/Modules/Logger.cpp
- src/Components/Modules/Menus.cpp
- src/Components/Modules/Node.cpp
- src/Components/Modules/Party.cpp
- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/RCon.cpp
- src/Components/Modules/RawFiles.cpp
- src/Components/Modules/ServerCommands.cpp
- src/Components/Modules/Weapon.cpp
- src/Components/Modules/ZoneBuilder.cpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
S1x/Open IW5 code (I recently committed), easy port.
> [Command] Refactor

- src/Utils/Library.hpp
Still crashes the client apparently
> Fully reverse changes to library component

- src/Utils/String.cpp
- src/Utils/String.hpp
Prevent undefined behaviour although very unlikely.
> [String] Port changes from S1x

- src/Components/Modules/Bots.cpp
- src/Components/Modules/Bots.hpp
- src/Components/Modules/Gamepad.cpp
- Bonus, small correction of comment I made in gamepad module some time ago I noticed when I was coby basting something.
> [Bots] Make requested changes by ineedbots

- src/Components/Modules/ScriptExtension.cpp
- src/Components/Modules/ScriptExtension.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
iw5-gsc-utils was mildly plagiarised.
[iw5-gsc-utils](https://github.com/fedddddd/iw5-gsc-utils)
> Expose entity/client flags to gsc

- CHANGELOG.md
- README.md
Remove ghost references to long deleted premake5 options
> Update markdown files

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/RawMouse.cpp
- src/Components/Modules/RawMouse.hpp
- src/Components/Modules/Window.cpp
- src/Components/Modules/Window.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
And enable dpi awareness for game window.
Should improve mouse accuracy 
PS: should fixes mouse accelaction issue when mouse polling rate > 125Hz on iw6x/s1x (going to port this now
> Add RawMouse Compoment

- src/Components/Modules/Script.cpp
> Fix issue with get system milliseconds

- src/Components/Modules/Bots.cpp
- src/Components/Modules/Bots.hpp
(next time update tr1ck sh0t menu?)
> [Bots] Add isBot GSC meth back

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Ceg.cpp
- src/Components/Modules/Ceg.hpp
- src/Utils/Hooking.cpp
- src/Utils/Hooking.hpp
If anything, this should improve performance because these checks don't run anymore.
> Remove (CEG?) functions

- deps/premake/json11.lua
- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Bots.cpp
- src/Components/Modules/ServerList.cpp
- src/Components/Modules/ServerList.hpp
- src/Components/Modules/UserInfo.cpp
- src/Components/Modules/UserInfo.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Utils/InfoString.cpp
- src/Utils/InfoString.hpp
All credits for the code go to [fed](https://github.com/fedddddd)
> [Script] Add way to modify player name

- src/Components/Modules/CardTitles.cpp
- src/Components/Modules/Chat.cpp
- src/Components/Modules/Chat.hpp
- src/Components/Modules/Clantags.cpp
- src/Components/Modules/ClientCommand.cpp
- src/Components/Modules/Dedicated.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
cod4x takes credit for the idea but I quickly wrote the code
> [Chat] add dvar to disable chat

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Bans.cpp
- src/Components/Modules/Logger.cpp
- src/Components/Modules/MapRotation.cpp
- src/Components/Modules/MapRotation.hpp
- src/Components/Modules/QuickPatch.cpp
> Allow people to go over 1024 limit on the map rotation

- CHANGELOG.md
- src/Components/Modules/MapRotation.cpp
- src/Components/Modules/MapRotation.hpp
Updated the changelog so we can say we 'fixed' it in a later release
> [MapRotation] Some backwards compatibility

- src/Components/Modules/Network.cpp
- src/Components/Modules/Node.cpp
- src/Components/Modules/ServerList.cpp
- src/Components/Modules/Session.cpp
The server pipeline is not running when sitting in the main menu
> [Node] Use Main pipeline

- src/Components/Modules/AssetHandler.cpp
- src/Components/Modules/MapRotation.cpp
- src/Components/Modules/Weapon.cpp
- src/Components/Modules/Weapon.hpp
- src/Game/Structs.hpp
Game::PWF_DISABLE_WEAPON_PICKUP does not work in asm stubs but the using directive does. MSVC quirk
> DisableWeaponPickup & EnableWeaponPickup

- src/Components/Modules/Renderer.cpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/STDInclude.hpp
- src/Utils/Maths.cpp
- src/Utils/Maths.hpp
- src/Utils/Utils.cpp
- src/Utils/Utils.hpp
Aims to reorganize the now messy (imo) Utils file
> [General] Quick Maths

- src/Components/Modules/Console.cpp
- src/Components/Modules/Console.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
Very useful, corrects some things in the module as well.
> [Console] Add very useful debugging function

- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/QuickPatch.hpp
- src/Components/Modules/VisionFile.cpp
- src/Components/Modules/VisionFile.hpp
- src/Components/Modules/Zones.cpp
- src/Components/Modules/Zones.hpp
- src/Game/Structs.hpp
- src/Utils/String.cpp
- src/Utils/String.hpp
> [VisionFile] Move zone patch here

- CHANGELOG.md
- src/Components/Modules/AssetInterfaces/Isnd_alias_list_t.cpp
- src/Components/Modules/Bans.cpp
- src/Components/Modules/ServerInfo.cpp
- src/Components/Modules/ServerList.cpp
- src/Components/Modules/Theatre.cpp
- src/Utils/InfoString.cpp
Fixes bug reported in iw4x-modding discord channel
> Fixes for JSON

- src/Components/Modules/Friends.cpp
- src/Components/Modules/Friends.hpp
- src/Steam/Interfaces/SteamFriends.cpp
- src/Steam/Interfaces/SteamFriends.hpp
> [Friends] Remove code that forces you to be busy on Steam

- src/DllMain.cpp
- src/Utils/Cache.cpp
- src/Utils/Cache.hpp
As laupetin said, this is really bad practice that needs to be fixed.
> Do not clear a static variable

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Auth.cpp
- src/Components/Modules/ClanTags.hpp
- src/Components/Modules/Console.cpp
- src/Components/Modules/Network.cpp
- src/Components/Modules/Security.cpp
- src/Components/Modules/Stats.cpp
- src/Components/Modules/Theatre.cpp
- src/Components/Modules/Voice.cpp
- src/Components/Modules/Voice.hpp
- src/Game/Dvars.cpp
- src/Game/Dvars.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
> [Voice] Voice chat

- src/Components/Modules/Console.cpp
- src/Components/Modules/Console.hpp
> [Console] Remove duped code

- src/Components/Modules/ClientCommand.cpp
- src/Components/Modules/Command.cpp
- src/Components/Modules/GSC/Int64.cpp
- src/Components/Modules/GSC/Script.cpp
- src/Components/Modules/GSC/ScriptExtension.cpp
- src/Components/Modules/UIScript.cpp
- src/Components/Modules/Vote.cpp
TOP -5 refactoring PRs of all time
> got -> itr

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/Threading.cpp
- src/Components/Modules/Threading.hpp
- src/Game/Server.cpp
- src/Game/Server.hpp
> [Threading]: Removing this was not a good idea

- src/Components/Modules/Download.cpp
- src/Components/Modules/GSC/Script.cpp
- src/Components/Modules/GSC/Script.hpp
- src/Components/Modules/Voice.cpp
**How does this PR change IW4x's behaviour?**
I don't know
> [Download]: Update Download.cpp

- src/Components/Modules/AssetInterfaces/IRawFile.cpp
- src/Components/Modules/ZoneBuilder.cpp
> [RawFile]: Remove copy & pasted code

- src/Components/Modules/Renderer.cpp
> Draw model name in its ground color if relevant

- src/Components/Modules/Maps.cpp
- src/Components/Modules/PlayerMovement.cpp
- src/Components/Modules/PlayerMovement.hpp
(The nothing else has been thoroughly tested)
> Add cod4 map to dlc list (and absolutely nothing else)

- src/Components/Modules/GSC/IO.cpp
Credit to @DoktorSAS for allowing me to find this issue
> [IO]: Truncate file length

- deps/premake/iw4-open-formats.lua
- src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
- src/Components/Modules/AssetInterfaces/IclipMap_t.cpp
- src/Components/Modules/Maps.cpp
- src/Components/Modules/Maps.hpp
- src/Components/Modules/ZoneBuilder.cpp
- src/Components/Modules/ZoneBuilder.hpp
- src/Game/Database.cpp
- src/Game/Structs.hpp
Some stuff we forgot or messed up
> IW4Of Fixes

- src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
- src/Components/Modules/ZoneBuilder.cpp
maybe if we did reviews the normal way instead of directly writing onto each other's branches....
> Revert diamantes last minute modifications

- src/Components/Modules/AssetInterfaces/IFxEffectDef.cpp
- src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
- src/Components/Modules/AssetInterfaces/ISndCurve.cpp
- src/Components/Modules/AssetInterfaces/Isnd_alias_list_t.cpp
- src/Components/Modules/ZoneBuilder.cpp
> Fix snd/sndcurve not using original assets as fallback, bump IW4Of
