XLabsProject/iw4x-client

- CHANGELOG.md
- src/Components/Modules/Stats.cpp
- src/Components/Modules/Stats.hpp
Add support for mod-specific stat files. This allows mods to update the playerDataDef and allows the creation of classes with custom weapons per mod.
> Add support for mod-specific stat files

- src/Components/Modules/Zones.cpp
- src/Steam/Proxy.cpp
- Fix for the game trying to decrypt all read files instead of just encrypted images, also fixes a crash when loading mods due to the game trying to decrypt the gsc files.
- Ugly fix for the game crashing with the latest version of steam (credits to IceNinjaman).
> Fixes to image decryption check, the game crashing with mods loaded and the latest steam update causing the game to crash

- src/Components/Modules/Auth.cpp
- src/Components/Modules/D3D9Ex.cpp
- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/Stats.cpp
- Make mod-specific stats toggleable via a dvar and disable it by default
- Disable D3D9Ex by default as it causes the client to not vid_restart correctly for many people
- Add more guids from shitty repacks that include a guid
> Some improvements

- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/QuickPatch.hpp
fixes #43 
Fixed exception in G_GetClientScore that would happen when the function was called before the game was initialised, such as by IW4x's http server endpoint /info
> [QuickPatch] Fix crash in G_GetClientScore

- src/Components/Modules/Dvar.cpp
This probably is only useful to ultra wide / tripple monitor users as it allows them to force the menu / hud to be in the middle / on the middle monitor.
> Unlocked safeArea_horizontal and safeArea_vertical

- src/Components/Modules/Menus.cpp
- src/Steam/Steam.cpp
The latest steam update has broke IW4x's steam integration. As of now the best way of dealing with this is to just disable it. The code has been commented out so that in the future if fixed, this may easily be enabled once again.
> disable steam for now + add custom title menu

- src/Components/Modules/Script.cpp
- src/Components/Modules/Script.hpp
When developer dvar is > 0  a user will see script runtime errors and the source gsc file of the error.
> Adds printing script runtime errors when in developer

- src/Components/Modules/Download.cpp
- src/Components/Modules/Script.hpp
The HTTP GSC is only executable if -scriptablehttp or -dedicated flags are enabled. This is just so it prevents GSC code from not being compilable when the flags are not present.
> Register the GSC HTTP functions reguardless of being in Dedicated to prevent Script Compile Error

- src/Components/Modules/Script.cpp
Make iw4x developers life easier by not freezing their game up for GSC errors in basegame GSCs 🗡️ 
I understand why this feature exists, but it makes developing for iw4x impossible unless you comment it out - so maybe it doesn't belong on graphical clients.
> Do not interrupt gameplay for GSC errors

- src/Components/Modules/News.cpp
I've changed usernames from Jawesome99 to Emosewaj a while ago, relying on GitHub to keep the redirect up forever isn't a smart idea.
> Use new URL for Wiki

- src/Components/Modules/Zones.cpp
- src/Components/Modules/Zones.hpp
Without this, awp_arena cannot load in debug mode (and loads with errors on release I assume)
because Shellshock files on CODO do not use keywords, but the string table number instead (arbitrary numbers)
Same thing happens for visionfiles but @GEEKiDoS  has something worked out, maybe he will create the PR? will ask him
> Parse shellshock for 461+ CODO maps (only for awp_arena so far ?)

- src/Components/Modules/ZoneBuilder.cpp
IW4x-specific zone serve no purpose anymore in an open source project, so ZB should not generate them by default. 
This will make cod4-ported maps readable by any existing zone manager/dumper.
A macro is still defined in case a developer wants to build a version of zonetool that can still write these formats.
Reading is unaffected and previously-built zones will still be readable with this modification
See https://github.com/XLabsProject/iw4x-rawfiles/pull/1
> Unless explicitely defined, do not generate iw4x specific zones

- src/Components/Modules/Network.cpp
- src/Components/Modules/RCon.cpp
Might be better to use a switch that tells us if we're in a party or not, but Party::IsInLobby doesn't do it and the clientstate is `CS_FREE` even though we're connected and speaking - so this works, and works properly, I guess that's enough :D
> Fix rcon not working properly on party servers

- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/ZoneBuilder.cpp
- src/Components/Modules/ZoneBuilder.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
This will allow another hook to actually be called (was skipped before this commit) and sync fs shutdown.
Also removed unused function (another function replaces it #96 ).
Proper quit command added. It will call com quit f just like s1x.
> Removed hook inside com quit fs. 

- src/Utils/Library.cpp
This commit does not change code functionality. It should bring more consistency to the file modified because the class member variable module is always accessed directly without using the getter function.
> No need to use getter function inside class function

- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/QuickPatch.hpp
- src/Components/Modules/Zones.cpp
- src/Components/Modules/Zones.hpp
CODO has additional specops entities that mw2 doesn't know how to manage, which adds weird hitboxes on some multiplayer maps. This code prevents them from loading... but i'm not really satisfied with it. It's not using Zones::Version, although it should, but for some reason the version is always late (it works on second load, but not on the first one), maybe this happens too soon in the loading process? Would be surprising 
would love to get some input on it.
> Skip specops entities

- src/Components/Modules/AssetHandler.cpp
- src/Components/Modules/Colors.cpp
- src/Components/Modules/Colors.hpp
- src/Components/Modules/Localization.cpp
- src/Game/Functions.cpp
- src/Game/Structs.hpp
I could use a CFG for this, but since the colors are set from GSC, possibly in multiple places, that would require modifying _them_ and so... well i think it's good colorblind people are allowed to enforce whatever color they need on their client, regardless of what the server owner decided, i suppose? 🤔  :)
> colorblind friendly team colors!

- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/QuickPatch.hpp
The patch doesn't respect that the return type should be 32bit BOOL and has a 8bit bool instead.
That causes a game freeze or kick into main menu on loading into private match when in Release mode.
This is due to compiler optimizations not setting the whole 32bit value when returning.
> Fix codol dynent patch bug

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/SoundMutexFix.cpp
- src/Components/Modules/SoundMutexFix.hpp
This is a fix for https://github.com/XLabsProject/iw4x-client/issues/80, or rather a workaround.
For reasons explicited in the code, it works "enough" to mitigate the issue and avoid all crashes related to the miles mutex problem, as far as I know.
I've been playing multiple games with this fix for two months with no notable problems, except maybe a slight freeze on round intermission from time to time (was that an avoided crash?). I'm not even sure this was due to the fix or just something that would have occured regardless :D 
So as far as I know this is "safe", but it's also "not great", so - i'm leaving the issue open and hopefully someone can one day come up with a better fix. Kudos to @Laupetin  for helping me investigate this through!
> Sound mutex workaround

- src/Components/Modules/ServerList.cpp
Filter out any server that answer with a server info that specifies a player count that is greater than 18 or lower than 0.
> Ignore servers in serverlist that specify an invalid player count

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Dedicated.hpp
- src/Components/Modules/Materials.cpp
- src/Components/Modules/ServerList.cpp
Make sure that material text icons that are not 2D do not cause issues anymore.
Also strips material text icons entirely for chat messages and server names in the serverlist.
> Fix 2d material text icons

- src/Components/Modules/Gamepad.cpp
- src/Components/Modules/Gamepad.hpp
- src/Components/Modules/Localization.cpp
This swaps localized button textures from their xbox versions to their playstation versions whenever the style dvar is set to 1
> Add Playstation style flavor to gamepad buttons

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Dvar.cpp
- src/Components/Modules/Movement.cpp
- src/Components/Modules/Movement.hpp
- src/Game/Structs.hpp
- This PR adds two new Dvars. The player_lastStandCrawlSpeedScale Dvar was already present in the game for debugging purposes. I originally wrote this code for IW5 and since the folks at pluto liked the idea I think it will be part of their client in some next future release. I ported the code to IW4 as well because I think this kind of customization can be beneficial to the client. I thoroughly tested the code on IW5 and I briefly tested it on IW4 because the code is identical.
- The new Dvars will affect how fast the player moves when he is in the prone stance, ducked stance or in the last stand stance. A single Dvar only affects the speed of the player when he is in that specific stance. For example, the player walking speed will be unaffected by changes to these Dvars. Changing the …
> [Movement] Add customizable speed scale for stance

- src/Components/Modules/QuickPatch.cpp
- src/Components/Modules/QuickPatch.hpp
- src/Game/Functions.hpp
In light of a recent pull request, it came to my attention that some things were done incorrectly in the QuickPatch module.
This pr should be beneficial because:
- A vector is no longer being allocated when registering an enum dvar
- Added comments to InvalidNameCheckStub
- Replace the explicit call to strncpy with a call to actual game function. It was argued before that it is the best approach. (https://github.com/XLabsProject/iw4x-client/pull/92#discussion_r663989104).
- Proper use of const in InvalidNameCheck
- Use the dvar class wrapper when appropriate
> [QuickPatch] Quick Refactor

- src/Components/Modules/Bots.cpp
- src/Components/Modules/Download.cpp
- src/Components/Modules/Script.cpp
- src/Components/Modules/Script.hpp
- src/Components/Modules/Slowmotion.cpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Structs.hpp
- Corrected function signature for `Scr_GetNumParam` and `Scr_GetType`, which means I fixed signed/unsigned mismatch.
- If a function gets detoured more than once a warning is printed. I don't know how to make the warning message more specific at the moment. I honestly would prefer if instead of a warning an error is thrown by `Scr_Error` or detouring more than once the same function was not permitted but I kept it like `Evan ☆/Eve` suggested on discord. Let me know if that's okay.
Code was tested by hooking a few functions, it works as intended. 
```
init() // Or main()
{
replaceFunc( maps\mp\perks\_perkfunctions::GlowStickDamageListener, ::GlowStickDamageListenerHook );
}
GlowStickDamageListenerHook( owner )
{
// Write your own code here
}
```
* [fedddddd](https://github.com/fedddddd) - …
> [Script] Add ReplaceFunc Game Script Function

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Dedicated.hpp
- src/STDInclude.hpp
Adds `sv_randomMapRotation` bool dvar. If set to true and `sv_mapRotationCurrent` is empty (when the server starts for the first time), the map rotation will be randomized.
So the new function will take as input key/value pairs from `sv_mapRotation` where the key is either `map` or `gametype` and the value can be the name of the map or the name for the `gametype`.
Every pair of the key/value will be shuffled, so game mode changes and the position of the maps in `sv_mapRotation` is random. I tested the code a couple of times, and at every startup of my dedicated server, the string value of the map rotation Dvar was different each time.
If merged, #105 can be closed.
As mentioned by the issue, the idea of implementing this feature comes from CoD4x_Server, but the code itself does not. …
> [Dedicated] Add random map rotation

- src/Components/Loader.cpp
- src/Components/Loader.hpp
- src/Components/Modules/Elevators.cpp
- src/Components/Modules/Elevators.hpp
A stub is added inside PM_GroundTrace, it will allow skipping the only call to PM_CorrectAllSolidStub (if the sv_disableElevators Dvar is set to 1) and will disable elevators. This feature should be welcomed by server owners that don't want people to glitch out of maps.
- sv_disableElevators: default to false so elevators are only disabled if it's set to 1 by the server owner. Dvar is cheat protected and replicated as it should be imo
sv_disableElevators follows the principles described here: [Research](https://xoxor4d.github.io/research/mw2-elevator/).
To recap, xoxor4d observes that skipping a call to PM_CorrectAllSolid or PM_JitterPoint in later Cods disables elevators.
* [xoxor4d](https://github.com/xoxor4d)
- Matrix for general feedback
> [Feature] Add options to disable elevators

- src/Components/Modules/Elevators.cpp
Add prone elevators to the easy settings.
If elevators are set to easy the new hooked function will make sure the ducked + prone flags are always removed from player state
> [Elevators] Add prone elevators

- src/Components/Modules/StartupMessages.cpp
- src/Components/Modules/StartupMessages.hpp
A quick glance at the c++ standard reveals that std::list::front returns a reference to the first element, while pop_front removes it invaliding the reference, of course.
A quick refactor allows us to avoid the unintentional copy of the string and then I also clear the list in the deconstructor of the class as it is the norm in all the other modules.
> Refactor startup messages

- src/Components/Modules/Command.cpp
- src/Components/Modules/Command.hpp
- src/Components/Modules/Dvar.cpp
- src/Components/Modules/Friends.cpp
- src/Components/Modules/Playlist.cpp
- src/Components/Modules/UIScript.cpp
- src/Components/Modules/ZoneBuilder.cpp
- src/Game/Functions.cpp
Let's use const char*
🥶 🍦
Removed template char* getter function from a bunch of modules as it can't be a good idea to convert a `const char*` string (for example `this->dvar->current.string`) to a `char*` like you wouldn't want to accidentally modify those strings.
PS
`std::pow(vec[0], 2.0f)` is slow while `vec[0] * vec[0]` is faster. It is also what the game's Vec3Normalize function does.
> Partially revert some changes from "fix compile errors on c++20"

- src/Components/Modules/ClientCommand.cpp
- src/Components/Modules/Command.cpp
Restore setviewpos command as it should be.
This pr removes setviewpos from the command module as its implementation is wrong (only works in private match).
The new command is handled by the client-command handler and behaves like IW's implementation on other versions of the game where the function is present (The game original handler for the client-command setviewpos was removed in the version of the game IW4x uses).
> Restore setviewpos command

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Dedicated.hpp
This is usually how s1x and iw6x override dvars
> [Dedicated] Fix questionable patch

- src/Components/Modules/Dvar.cpp
- src/Components/Modules/Dvar.hpp
- src/Components/Modules/Gamepad.cpp
- src/Components/Modules/Gamepad.hpp
- src/Game/Functions.hpp
Petition to replace
`aim_turnrate_pitch_ads = Dvar::Var("aim_turnrate_pitch_ads");`
with
`aim_turnrate_pitch_ads = Dvar::Var(0x0);` <- replace with the actual address of where the pointer is stored
> Fix gamepad vars

- src/Components/Modules/QuickPatch.cpp
- src/Utils/Library.cpp
- src/Utils/Library.hpp
Refactor quick path so matlog is removed unless debug.
Also make the library module behave similarly to s1x's.
> Refactor quickpatch

- src/Components/Modules/FileSystem.cpp
- src/Components/Modules/Logger.cpp
- src/Game/Functions.hpp
The game functions that our logger hooks will not ever use a buffer larger than 4096 bytes.
Also, IW4x does not seem to need such a large buffer (on the heap). 4096 is plenty, and faster because now it's on the stack.
> Logger improvements

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Node.cpp
- src/Components/Modules/ServerList.cpp
- src/Components/Modules/ServerList.hpp
this will probably spark a discussion, but after talking to Jebus, I'm pretty sure this should happen. this uses `master.xlabs.dev:20810` as the master server already has support for IW4x and if the master server is not reached within 5 seconds, a toast will appear notifying that node is being used and will fallback to using node servers. node doesn't get used on the client until this point is reached. node is then disabled once going back into the server browser again.
im no expert at c++, so please review
> Use master server, fallback to node if not reached

- src/Components/Modules/Gamepad.cpp
- Make dvars gpad_present, gpad_in_use readonly since they should only be set from cpp code
- Make dvars gpad_stick_pressed_hysteresis, gpad_stick_pressed, gpad_stick_deadzone_max, gpad_stick_deadzone_min, gpad_button_deadzone, gpad_button_lstick_deflect_max, gpad_button_rstick_deflect_max, gpad_use_hold_time saved to config to make it easier for user to configure them
> Update gamepad patch dvar flags

- src/Components/Modules/Gamepad.cpp
- src/Components/Modules/Gamepad.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
Before keystrokes in an active bind field could not bind controller keys because the values of the remapped menu keys were taken.
Now all controller buttons can be rebound using these menu fields.
The menu fields show KBM keys whenever KBM is used and gamepad keys whenever gamepad is in use.
Additionally whenever a gamepad button is rebound using a menu field, the button config is set to custom so the gamepad options show an empty value (indicating custom values) for button layout
> Make keybind fields in menus work with controller keys

- src/Components/Modules/ServerList.cpp
- src/Components/Modules/ServerList.hpp
this should fix changing the source (Internet, Local, Favorites) category of the server list and having servers still in the list and visible list not properly working. this reimplements the refreshing on visible list, but it must be specified to refresh. default value for refresh is false as defined in the header.
> fix visible server list refreshing

- src/Components/Modules/Console.cpp
Removed the need to use '\' or '/' to send a command in the console. The say command via console is redundant and serves no purpose.
> Improve console usability

- src/Components/Modules/Gamepad.cpp
Fixes #276
Reimplementation of key lookup didn't initialize key indices like the game does since they get used even though returned key count is 0 or 1 in case the backspace key is pressed.
> Fix crash on clearing keys via menus

- src/Components/Modules/Script.cpp
- src/Components/Modules/Script.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
This enhances the loading code, currently, if a script does not have a function called 'init' or 'main' a sort of warning is printed to indicate that both are missing. This doesn't need to happen as custom scripts can have custom entry points that are not necessarily called that way. Additionally, a community member made a request some time ago to have custom scripts with both 'main' and 'init' functions load both and not just 'init'. This promotes script compatibility with other clients.
> [Script] (feature request): Enchance script loading

- src/Components/Modules/Logger.cpp
- src/Components/Modules/Logger.hpp
- src/Components/Modules/Theatre.cpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
Thanks to Raidmax, another bug was found and squashed.
This makes the output of logger::print match what it was pre-c++20 (std::format) logger.
Also allows people to receive network logs even if the logfile was not opened
> [Logger] Fix output by g_log_list & log_list

- src/Components/Modules/ClanTags.cpp
- src/Components/Modules/ClanTags.hpp
that must not be called when in-game
> [ClanTags] Remove hooked function

- src/Components/Modules/AssetInterfaces/IMaterial.cpp
- src/Components/Modules/ZoneBuilder.cpp
Just an addition to the techswap table + use zb assets by default cause not doing so is nonsense & causing problems too often. We keep the option to use in-memory assets though for backward compatibility
> Fix crash snow

- src/Components/Modules/Maps.cpp
- src/Components/Modules/Maps.hpp
Vanilla maps don't need team FF, so let the arena specify if it's needed or not and if not let's not load additional zones for nothing.
This improves loading time by quite a bit i've heard.
Tested on iw3 and iw4 maps with success, but this still needs a bit more testing
> Disable additional zones for vanilla maps

- src/Components/Modules/GSC/ScriptExtension.cpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
Adds two new builtins
The reason for float is that it is present in IW5
The reason for Strtol is that it helps gsc modders avoid workarounds when converting a hexadecimal string to an integer like this one
.
> [Script] Strtol & Float

- src/Components/Modules/RCon.cpp
- src/Components/Modules/RCon.hpp
[Quake-III](https://github.com/id-Software/Quake-III-Arena/blob/master/code/server/sv_main.c#L443)
This is an enhanced patch as Q3 code is actually creating a DOS in it self.
It blindly limits all requests to one every 500ms meaning if just one request is sent constantly sent every 500 ms it will completely block all RCon traffic.
This patch will limit to *one* request *per* IP every *500ms* just like CoD4x
> [RCon]: Tidy up code

- src/Components/Modules/AssetInterfaces/IFxEffectDef.cpp
- src/Components/Modules/AssetInterfaces/IFxEffectDef.hpp
Oddly enough some IW5 maps (especially DLC) mention sound names that they do not have in their zones, and that aren't common sounds either. As such, these sounds are not dumped by OpenIW5+IW4OF, but they're still mentioned by name in the FX effect definition.
This causes a fatal error when building maps with zonebuilder as it expects every asset to be present during marking. But the truth is assets only mentioned by name need not to be present for the map to run. In fact once ingame, there's not even a missing asset error, so I suppose the FX themselves could be leftovers.
also i removed a bunch of deadcode i know you like it
> Ignore missing soundnames in FX
